# Generated by Django 4.1.7 on 2023-02-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_vehicle_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
